"""
Django settings for miproyecto project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

load_dotenv()  # cargar variables de .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pr82_ut6=oomkk*54q&v__z*xux260b$p&!%$58#cs=)e^mpa='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'saludo',  # la app saludo debe registrarse.
    'rest_framework',  # registrar la biblioteca
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miproyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miproyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.mysql',
      'NAME': os.getenv('NAME_DB_MARIA'),
      'USER': os.getenv('USER_DB_MARIA'),
      'PASSWORD': os.getenv('PASSWORD_DB_MARIA'),
      'HOST': os.getenv('HOST_DB_MARIA'),
      'PORT': os.getenv('PORT_DB_MARIA'),
    },
    'db_sqlite3': {
      # motor por defecto al crearse el proyecto
      'ENGINE': 'django.db.backends.sqlite3',
      # 'NAME': BASE_DIR / 'db_miproyecto.sqlite3',
      'NAME': BASE_DIR / os.getenv('NAMEDB_SQLITE3'),
    },
    'bd_postgresql': {
      """ configuración Standar para PostgreSQL
      'ENGINE': 'django.db.backends.postgresql',
      'NAME': 'app_db',
      'USER': 'postgres',
      'PASSWORD': 'tu_contraseña',
      'HOST': 'localhost',
      'PORT': '5432',
      """
      # uso de variables de entorno en .env
      'ENGINE': 'django.db.backends.postgresql',
      'NAME': os.getenv('NAME_BD_POSTGRESQL'),
      'USER': os.getenv('USER_BD_POSTGRESQL'),
      'PASSWORD': os.getenv('PASSWORD_BD_POSTGRESQL'),
      'HOST': os.getenv('HOST_BD_POSTGRESQL'),
      'PORT': os.getenv('PORT_BD_POSTGRESQL'),
    },
    'db_maria': {
      """
      'ENGINE': 'django.db.backends.mysql',
      'NAME': 'app_db',
      'USER': 'usuario',
      'PASSWORD': 'tu_contraseña',
      'HOST': 'localhost',
      'PORT': '3306',
      """
      # uso de variables de entorno en .env
      'ENGINE': 'django.db.backends.mysql',
      'NAME': os.getenv('NAME_DB_MARIA'),
      'USER': os.getenv('USER_DB_MARIA'),
      'PASSWORD': os.getenv('PASSWORD_DB_MARIA'),
      'HOST': os.getenv('HOST_DB_MARIA'),
      'PORT': os.getenv('PORT_DB_MARIA'),
    },
    'db_mysql': {
      """
      'ENGINE': 'django.db.backends.mysql',
      'NAME': 'app_db',
      'USER': 'usuario',
      'PASSWORD': 'tu_contraseña',
      'HOST': 'localhost',
      'PORT': '3306',
      """
      # uso de variables de entorno en .env
      'ENGINE': 'django.db.backends.mysql',
      'NAME': os.getenv('NAME_DB_MYSQL'),
      'USER': os.getenv('USER_DB_MYSQL'),
      'PASSWORD': os.getenv('PASSWORD_DB_MYSQL'),
      'HOST': os.getenv('HOST_db_mysql'),
      'PORT': os.getenv('PORT_db_mysql'),
    },
    'db_msserver': {
      """
      'ENGINE': 'mssql',
      'NAME': 'app_db',
      'USER': 'usuario',
      'PASSWORD': 'tu_contraseña',
      'HOST': 'localhost',
      'PORT': '1433',
      'OPTIONS': {
        'driver': 'ODBC Driver 17 for SQL Server',
      },
      """
      # uso de variables de entorno en .env
      'ENGINE': 'mssql',
      'NAME': os.getenv('NAME_DB_MSSERVER'),
      'USER': os.getenv('USER_DB_MSSERVER'),
      'PASSWORD': os.getenv('PASSWORD_DB_MSSERVER'),
      'HOST': os.getenv('HOST_DB_MSSERVER'),
      'PORT': os.getenv('PORT_DB_MSSERVER'),
      'OPTIONS': os.getenv('OPTIONS_DB_MSSERVER'),
    }

}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'  # formato standar original
LANGUAGE_CODE = 'es-ar'  # adecuacion al servidor y locale

# TIME_ZONE = 'UTC'  # formato standar original
TIME_ZONE = 'America/Argentina/Cordoba'  # adecuacion al servidor y locale

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
